add usage adn better error handling

diff --git a/build b/build
--- a/build
+++ b/build
@@ -1,16 +1,59 @@
 #! /usr/bin/env bash
 
-# This is an interactive script to build LibreSymbols extensions.
+# This is a script to build LibreSymbols extensions.
 #
 # LibreSymbols
 #
 # Stefan Schmidhuber (stefan.schmidhuber@gmx.at)
 
-# first parameter identifies the git tag
-if [ -z $1 ]; then
-  TAG="last"
-else
-  TAG=$1
+
+print_help() {
+  echo -e 'Usage: ./build [version]'
+  echo -e 'Build a LibreSymbols extension of the given version or the latest'
+  echo -e 'version if none is given. The optional  parameter "version" is a git tag.'  
+  exit 0
+}
+
+get_tag() {
+  if [ -z $1 ]; then
+    TAG="last"
+  else
+    TAG=$1
+  fi
+  
+  if [ $TAG = "last" ]; then
+    if [ $(git tag -l | wc -l) -gt 0 ]; then
+      TAG=$(git tag -l | tail -n 1)
+      return 0
+    else
+      echo -e 'ERROR: can not find any tag'
+      exit 1
+    fi
+  else
+    VALID="false"
+    for tmp in $(git tag -l); do
+      if [ $tmp = $TAG ]; then
+	return 0
+      fi
+    done
+    echo 'ERROR: invalid tag "'$TAG'"'
+    exit 1
+  fi      
+}
+
+
+# entry point
+
+if [ ! -z $1 ]; then
+  if [ $1 = "-h" ] || [ $1 = "-help" ] || [ $1 = "--help" ]; then
+    print_help
+  fi
 fi
 
+if [ $# -gt 1 ]; then
+  echo -e 'ERROR: Invalid number of arguments.\n'
+  print_help
+fi
+
+get_tag $1
 echo $TAG
